### ISSUE TITLE
cpp implementation for assignment 2?

### ISSUE THREAD

**Issue by Slyt4il** [Sunioatm/Image-Processing#1]
Is it missing? I can't find it anywhere.

**Comment by Slyt4il** [comment]
@Sunioatm Is this repo still maintained? Any progress on this and assignment 3?

**Comment by Sunioatm** [comment]
> Is it missing? I can't find it anywhere.

I'm not using cpp anymore so there won't be any from now on.

**Comment by Sunioatm** [comment]
> @Sunioatm Is this repo still maintained? Any progress on this and assignment 3?

For assignment 3 it not coming yet because this period is about to have the midterm exam. And I think you also have an exam too. So you shouldn't waste time on flagging my issue and go to read a book instead.

**Comment by Slyt4il** [comment]
Hey, it's all good. There's no need to be so defensive. I'll just close this issue. Cheers 👍
